version: '3.8'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local
