-- liquibase formatted sql

-- changeset Shulika619:1704391777691-1
CREATE TABLE person
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(25) NOT NULL,
    last_name  VARCHAR(25) NOT NULL,
    email      VARCHAR(55) NOT NULL UNIQUE,
    password   VARCHAR(55) NOT NULL
);

-- changeset Shulika619:1704391777691-2
CREATE TABLE task
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    status      VARCHAR(20) NOT NULL,
    priority    VARCHAR(20) NOT NULL,
    author_id   BIGINT NOT NULL REFERENCES person (id),
    executor_id BIGINT REFERENCES person (id)
);

-- changeset Shulika619:1704391777691-3
CREATE TABLE comment
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(1024) NOT NULL,
    task_id BIGINT NOT NULL REFERENCES task (id)
);
